#!/usr/bin/env python3

import socket

SERVER = 'irc.freenode.net'
PORT = 6667
NICK = 'example'
IDENT = 'example'
REALNAME = 'example'

# Create a socket and connect to the server
ircsock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
ircsock.connect((SERVER, PORT))

def ircsend(msg):
    """Send a message to the IRC server with proper formatting."""
    ircsock.send(bytes(msg + "\r\n", "UTF-8"))

# Send NICK and USER commands using ircsend
ircsend(f'NICK {NICK}')
ircsend(f'USER {IDENT} * * :{REALNAME}')

def ping(ping_msg):
    ircsend(f"PONG :{ping_msg}")

def get_irc_message():
    ircmsg = ircsock.recv(2048).decode("UTF-8")
    ircmsg = ircmsg.strip('\n\r')
    return ircmsg

while True:
    ircmsg = get_irc_message()
    print(ircmsg)

    if ircmsg.startswith("PING :"):
        ping_msg = ircmsg.split(":", 1)[1]
        ping(ping_msg)
